name: wandering_path
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
version: 0.0.1
description: >
  Drawing a path of random number of segments, each having a random number of lines.
dependencies:
  browser: any
